### ISSUE TITLE
What is the purpose of qinghuai?

### ISSUE THREAD

**Issue by xiang90** [qinghuaiorg/co-founder#4]
If this website is targeting at tech news from foreign media, it will probably create friction and will not get a lot of attention. I will still go to hacker news anyway. 

I am more interested in finding a way to foster the hacker and tech atmosphere in Chinese community.

**Comment by tvvocold** [comment]
Nice question, this site is Not targeting at foreign tech news, but focus on China's tech news or info.
About foster the hacker and tech atmosphere in Chinese community, we will find out.

BTW, welcome aboard!

Cheers,
Ray
