### ISSUE TITLE
想知道为什么1.qinghuai.org会跳到http://hack.fdzh.org/

### ISSUE THREAD

**Issue by jiacai2050** [qinghuaiorg/co-founder#7]
并且事前没有什么提示？那么之前的账号的数据是不是也就没了呢？

**Comment by tvvocold** [comment]
hi @jiacai2050 ,
由于主机商（linode）那边经常出问题（坑），qinghuai.org 不再维护了，实在抱歉。

**Comment by jiacai2050** [comment]
好吧，只是觉得有些突兀了，而且之前也没有公告说要关，只觉得“情怀”两个字真是被滥用了。

不管怎样，谢谢你曾经提供了这么个地方。
祝今后一切顺利

**Comment by tvvocold** [comment]
：）

**Comment by 1dot75cm** [comment]
hack.fdzh.org 也是一个有情怀的地方。

话说 qinghuai.org 用社区的服务器不就行了？
